name: corsac_jwt
version: 0.2.2
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  asn1lib: "^0.6.4"
  logging: "^0.11.3"
  pointycastle: "^2.0.1"
  rsa_pkcs: "^1.1.2"
  crypto: "^2.0.0"

dev_dependencies:
  test: "^1.0.0"
  test_coverage: any
  pedantic: "^1.8.0"
